name: RegionWarp
main: de.philworld.bukkit.regionwarp.RegionWarp
version: $MAVEN-VERSION-NUMBER$
depend:
   - WorldGuard
   - WorldEdit
   
commands:
    reg:
        description: Warp to the specified region
        usage: /reg <REGION_NAME>

permissions:
    regionwarp.all:
      description: A user can warp to all regions.
      default: op
    regionwarp.owner:
      description: A user can warp to its own regions (where he is the owner).
      default: op
    regionwarp.member:
      description: A user can warp to regions where he is a member.
      default: op